// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title IVerifier
 * @dev This is the interface for the ZK-SNARK verifier contract that will be
 *      auto-generated by a tool like snarkjs. Our main contract will call this.
 */
interface IVerifier {
    function verifyProof(
        uint256[2] memory a,
        uint256[2][2] memory b,
        uint256[2] memory c,
        uint256[4] memory input // We expect 4 public inputs for our vote
    ) external view returns (bool);
}

/**
 * @title MultiCandidateVoting
 * @author Your Name (for your thesis!)
 * @notice A smart contract to manage multiple elections, each with multiple candidates,
 *         secured by ZK-SNARKs for voter anonymity.
 */
contract MultiCandidateVoting {

    // =========================================================================
    // State Variables
    // =========================================================================

    IVerifier public immutable verifier; // The ZK proof verifier contract

    // --- Poll Data Structures ---

    struct Poll {
        uint256 id;
        string title;
        uint256 numCandidates; // The number of valid choices for this poll
        bytes32 merkleRoot;    // The cryptographic fingerprint of the eligible voter list
        uint256 totalVotes;    // Total votes cast in this poll
        bool isActive;         // A flag to start/stop voting
    }

    uint256 public pollCounter;
    mapping(uint256 => Poll) public polls; // pollId => Poll details

    // --- Vote & Nullifier Storage ---
    // Note: Mappings cannot be in structs, so we store counts and nullifiers here.

    // pollId => candidateId => vote count
    mapping(uint256 => mapping(uint256 => uint256)) public pollVoteCounts;

    // pollId => nullifierHash => boolean (true if used)
    mapping(uint256 => mapping(uint256 => bool)) public usedNullifiers;
    
    // --- Access Control ---
    address public owner;


    // =========================================================================
    // Events & Errors
    // =========================================================================

    event PollCreated(uint256 indexed pollId, string title, uint256 numCandidates);
    event VoteCast(uint256 indexed pollId, uint256 indexed candidateId);
    event PollStatusChanged(uint256 indexed pollId, bool isActive);

    error NotOwner();
    error PollNotActive();
    error InvalidCandidateId();
    error PollDoesNotExist();
    error AlreadyVoted();
    error InvalidProof();

    // =========================================================================
    // Constructor & Modifiers
    // =========================================================================

    constructor(address _verifierAddress) {
        verifier = IVerifier(_verifierAddress);
        owner = msg.sender;
    }

    modifier onlyOwner() {
        if (msg.sender != owner) revert NotOwner();
        _;
    }

    // =========================================================================
    // Administrative Functions
    // =========================================================================

    /**
     * @notice Creates a new poll for voting. Only the owner can call this.
     * @param _title The title or proposal text of the poll.
     * @param _numCandidates The number of choices available (e.g., 5 candidates means IDs 0-4 are valid).
     * @param _merkleRoot The Merkle root of the list of eligible voters for this specific poll.
     */
    function createPoll(
        string memory _title,
        uint256 _numCandidates,
        bytes32 _merkleRoot
    ) external onlyOwner {
        pollCounter++;
        uint256 newPollId = pollCounter;

        polls[newPollId] = Poll({
            id: newPollId,
            title: _title,
            numCandidates: _numCandidates,
            merkleRoot: _merkleRoot,
            totalVotes: 0,
            isActive: true
        });

        emit PollCreated(newPollId, _title, _numCandidates);
    }
    
    /**
     * @notice Toggles the active state of a poll.
     */
    function setPollActive(uint256 _pollId, bool _isActive) external onlyOwner {
        if (polls[_pollId].id == 0) revert PollDoesNotExist();
        polls[_pollId].isActive = _isActive;
        emit PollStatusChanged(_pollId, _isActive);
    }


    // =========================================================================
    // Core Voting Logic
    // =========================================================================

    /**
     * @notice Cast a vote for a specific candidate in a specific poll.
     * @dev This function expects a ZK-SNARK proof that verifies the voter's
     *      eligibility and uniqueness without revealing their identity.
     * @param _pollId The ID of the poll to vote in.
     * @param _proof_a, _proof_b, _proof_c The components of the ZK-SNARK proof.
     * @param _publicInputs An array of public signals used by the proof. Expected order:
     *        [0]: merkleRoot - The root of the voter list.
     *        [1]: nullifierHash - To prevent double-voting.
     *        [2]: voteCandidateId - The candidate ID the user is voting for.
     *        [3]: pollId - To ensure the proof is for this specific poll.
     */
    function castVote(
        uint256 _pollId,
        uint256[2] memory _proof_a,
        uint256[2][2] memory _proof_b,
        uint256[2] memory _proof_c,
        uint256[4] memory _publicInputs
    ) external {
        Poll storage currentPoll = polls[_pollId];
        
        // --- Pre-Verification Checks ---
        if (currentPoll.id == 0) revert PollDoesNotExist();
        if (!currentPoll.isActive) revert PollNotActive();

        bytes32 merkleRoot = bytes32(_publicInputs[0]);
        uint256 nullifierHash = _publicInputs[1];
        uint256 candidateId = _publicInputs[2];
        uint256 proofPollId = _publicInputs[3];

        if (usedNullifiers[_pollId][nullifierHash]) revert AlreadyVoted();
        if (candidateId >= currentPoll.numCandidates) revert InvalidCandidateId();
        if (merkleRoot != currentPoll.merkleRoot) revert InvalidProof(); // Proof is for the wrong voter list
        if (proofPollId != _pollId) revert InvalidProof(); // Proof is for the wrong poll

        // --- ZK-SNARK Verification ---
        // Call the verifier contract to check the proof's validity.
        bool isValid = verifier.verifyProof(_proof_a, _proof_b, _proof_c, _publicInputs);
        if (!isValid) revert InvalidProof();

        // --- State Updates ---
        // If all checks pass, record the vote.
        usedNullifiers[_pollId][nullifierHash] = true;
        pollVoteCounts[_pollId][candidateId]++;
        currentPoll.totalVotes++;

        emit VoteCast(_pollId, candidateId);
    }

    // =========================================================================
    // View Functions
    // =========================================================================
    
    /**
     * @notice Gets the vote count for a specific candidate in a poll.
     */
    function getVoteCount(uint256 _pollId, uint256 _candidateId) external view returns (uint256) {
        return pollVoteCounts[_pollId][_candidateId];
    }
}